### ISSUE TITLE
Usernames that are not on reddit still show up in the history

### ISSUE THREAD

**Issue by alantoch** [alexandruantochi/reddit-up#57]
History should get updated on a successful user data pull

**Comment by bastianrickmann** [comment]
you referring to the browser history right?

**Comment by alantoch** [comment]
![image](https://user-images.githubusercontent.com/14250073/227925580-414459de-1b71-4a93-b9ca-c08a40e3d3e3.png)

![image](https://user-images.githubusercontent.com/14250073/227925611-022fecc0-72f2-4345-b759-3f3059c7e922.png)

**Comment by bastianrickmann** [comment]
That's odd. When I saw the issue, I tested it and everything works fine. But I will check the code again. Maybe there is some weird edge case.

**Comment by bastianrickmann** [comment]
Seems like there is duplicated code checking for the user and handling errors different. This one seems to respond with user not found when the user only never posted something.

If you do the same thing with a more random name that for sure never someone used to create a test account on Reddit, then there should be a different error and they aren't added to the history.

**Comment by alantoch** [comment]
I'll create a new error that states the user has no posts then.
